# ==================
# Schedule API Calls
# ==================
###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=hydrations

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=broadcasts

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=decisions

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=flags

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=game(content(all))

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=game(promotions(all))

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=game(tickets(all))

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=gameId

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=gameInfo

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=homeRuns

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=linescore

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=lineups

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=officials

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=previousPlay

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=probablePitcher

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=review

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=ruleSettings

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=scoringplays

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=seriesStatus

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=statusFlag

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=story

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=team

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=trackingVersion

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=venue

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=weather

###
GET https://statsapi.mlb.com/api/v1/schedule?sportId=1&season=2026&teamId=144&date=2026-03-27&hydrate=xrefId

